version: "3.7"

services:
  vpn01:
    container_name: vpn01
    build:
      context: .
      dockerfile: Dockerfile
    image: vpnbase
    environment:
      - VPNFILE=vpn01.config
    network_mode: "host"
    privileged: true
    volumes:
          - type: bind
            source: ./
            target: /root