version: "3.7"

services:
  forticlient:
    build:
      context: .
      dockerfile: Dockerfile
    image: vpnbase
    network_mode: "host"
    privileged: true
    volumes:
          - type: bind
            source: ./
            target: /root